import Head from "next/head";
import Link from "next/link";

export const getStaticProps = async () => {
  console.log("\nGET_STATIC_PROPS FIRED !");
  return {
    props: { test: new Date().getTime() },
    revalidate: 5,
  };
};

export default function Home({ test }: { test: string }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Link href="/">Home </Link>
        <br />
        <Link href="/test">Test</Link>
        <p>Homepage - {test}</p>
      </main>
    </>
  );
}
